### ISSUE TITLE
Export to onnx

### ISSUE THREAD

**Issue by AnhPC03** [nipponjo/deepfillv2-pytorch#12]
Hello @nipponjo , I've exported your work to onnx but it didn't work
This is script
```
import torch

pretrained = "pretrained/states_pt_places2.pth"

generator_state_dict = torch.load(pretrained)['G']

if 'stage1.conv1.conv.weight' in generator_state_dict.keys():
    from model.networks import Generator
else:
    from model.networks_tf import Generator  

# set up network
generator = Generator(cnum_in=5, cnum=48, return_flow=False)

generator.load_state_dict(generator_state_dict, strict=True)

img = torch.rand([5, 512, 512]).unsqueeze(0).cpu()
mask = torch.empty(img.shape[0], 1, img.shape[2], img.shape[3]).cpu()
data = (img, mask)

generator.cpu().eval()

dynamic_axes = None
dynamic_export = True
if dynamic_export:
    dynamic_axes = {
        'input': {
            0: 'batch',
            2: 'height',
            3: 'width'
        },
        'output': {
            0: 'batch',
            2: 'height',
            3: 'width'
        }
    }
with torch.no_grad():
    torch.onnx.export(
        generator,
        data,
        "output.onnx",
        input_names=['input'],
        output_names=['output'],
        export_params=True,
        keep_initializers_as_inputs=False,
        verbose=False,
        opset_version=12,
        dynamic_axes=dynamic_axes)
print(f'Successfully exported ONNX model')
```
End the error was from ONNX
```
Traceback (most recent call last):
  File "deepfillv2-pytorch/export2onnx.py", line 65, in <module>
    torch.onnx.export(
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/miniconda3/envs/py39/lib/python3.9/site-packages/torch/onnx/symbolic_opset9.py", line 1281, in _convolution
    raise RuntimeError("Unsupported: ONNX export of convolution for kernel "
RuntimeError: Unsupported: ONNX export of convolution for kernel of unknown shape.
```
I've google it but they said that because there is an operation in pytorch that onnx doesn't support. But I could not investigate what operation.
Could you help me please? Thank you

**Comment by nipponjo** [comment]
Hello, onnx doesn't support the .view(..., -1, ...) shape inference that is used in `ContextualAttention`. 
You can easily replace  the -1's as shown here:
```python
L = raw_w.size(2)
raw_w = raw_w.view(raw_int_bs[0], raw_int_bs[1], kernel, kernel, L)
...
w = w.view(int_bs[0], int_bs[1], self.ksize, self.ksize, L)
...
m = m.view(int_ms[0], int_ms[1], self.ksize, self.ksize, L)

```

**Comment by awl-anht-nguyen** [comment]
Hi @nipponjo I've modified as you suggested but still got the same error. Could you help me check again please?

**Comment by nipponjo** [comment]
Hi, your script works for me after the modifications. I get the same error without them. I have attached my networks.py file.
[networks.py.txt](https://github.com/nipponjo/deepfillv2-pytorch/files/10706931/networks.py.txt)

**Comment by AnhPC03** [comment]
Hello @nipponjo, I've used your networks.py file but still got the same error. Could you share me your environment you used to convert?

**Comment by nipponjo** [comment]
Hello, I use the following versions:
```
fastapi==0.91.0
numpy==1.23.5
Pillow==9.4.0
PyYAML==6.0
torch==1.13.1+cu117
torchvision==0.14.1+cu117
uvicorn==0.20.0
```

**Comment by AnhPC03** [comment]
@nipponjo Did you install by using pip or conda? And which version of python you used?

**Comment by nipponjo** [comment]
I installed with pip and use python 3.9

**Comment by AnhPC03** [comment]
@nipponjo Thank you, I could export to ONNX successfully.
I'm very appreciate your help.

**Comment by awl-anht-nguyen** [comment]
Hi @nipponjo, Could you help me to convert your model to MNN please?

**Comment by AnhPC03** [comment]
Hi @nipponjo, Could you help me to convert your model to MNN please?
